name: Deploy Flask app

on:
  workflow_dispatch:

env:
    DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
jobs:
  
  deploy:
   runs-on: self-hosted       
   steps:
       - name: Code checkout
         uses: actions/checkout@v4

       - name:  deploy with docker compose
         run: docker compose up -d --build   