#This will deploy on server

on: 
    workflow_call:

jobs:

    deploy-server:
        runs-on: ubuntu-latest
        env:
         DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
         DOCKERHUB_TAG: ${{ github.sha }}

        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Docker login
              uses: docker/login-action@v3
              with:
               username: ${{ vars.DOCKERHUB_USER }}
               password: ${{ secrets.DOCKERHUB }}

            - name: SSH commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
               host: ${{ secrets.EC2_SSH_HOST }}
               username: ${{ secrets.EC2_SSH_USER }}
               key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
               script: |
                echo "Running Apps"
                export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                export DOCKERHUB_TAG=${{ github.sha }}
                echo ${{ github.sha }}
                docker login -u ${{ vars.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB }}
                mkdir -p /home/${{ secrets.EC2_SSH_USER }}/devsecops
                cd /home/${{ secrets.EC2_SSH_USER }}/devsecops

                cat > docker-compose.yml << 'EOF'
                
                services:
                 web:
                image: ${DOCKERHUB_USER}/github-actions-app:${DOCKERHUB_TAG}
                ports:
                 - '80:80'" 
                 
                EOF
                echo "----Verfiying File"
                cat docker-compose.yml
                
                ls -la
                docker compose -f docker-compose.yml down && docker compose -f docker-compose.yml up -d --force-recreate --pull always