#This will deploy on server

on: 
    workflow_call:

jobs:

    deploy-server:
        runs-on: ubuntu-latest
        env:
         DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
         DOCKERHUB_TAG: ${{ github.sha }}

        steps:
            - name: Code checkout
              uses: actions/checkout@v4

            - name: SSH commands using password  & create the folder
              uses: appleboy/ssh-action@v1.0.3
              with:
               host: ${{ secrets.EC2_SSH_HOST }}
               username: ${{ secrets.EC2_SSH_USER }}
               key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                echo "Starting the deployment process"
                sudo apt-get update && sudo apt-get install docker.io docker-compose-v2 -y
                sudo usermod -aG docker $USER && newgrp docker
                mkdir -p devsecops

            - name: Copy the docker compose fiel to the server
              uses: appleboy/scp-action@v1
              with:
               host: ${{ secrets.EC2_SSH_HOST }}
               username: ${{ secrets.EC2_SSH_USER }}
               key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
               source: docker-compose.yml
               target: ~/devsecops
            
            - name: SSH commands using password  & run the app
              uses: appleboy/ssh-action@v1.0.3
              with:
               host: ${{ secrets.EC2_SSH_HOST }}
               username: ${{ secrets.EC2_SSH_USER }}
               key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
               script: |
                echo "---Running the app----"
                 
                export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                export DOCKERHUB_TAG=${{ github.sha }}
                echo ${{ secrets.DOCKERHUB }} | docker login --username ${{ vars.DOCKERHUB_USER}} --password-stdin
                cd ~/devsecops &&docker compose down && docker compose up -d --build --force-recreate --pull always
                