#End to end pipline

name:  DevSecOps Pipeline
on:
    workflow_dispatch:

jobs:

    Code-Quality:
          uses: ./.github/workflows/code-quality.yml

    Secret-Scans:
          uses: ./.github/workflows/secret-scans.yml

    Dependices-Server:
          uses: ./.github/workflows/dependencies-scan.yml

    Docker-lint:
          uses: ./.github/workflows/docker-lint.yml

    Build:
          needs: [Code-Quality, Secret-Scans, Dependices-Server, Docker-lint]
          uses: ./.github/workflows/Deploy-server.yml
          secrets: inherit

    Trivy:
         needs: [Build]
         uses: ./.github/workflows/image-scan.yml
         secrets: inherit

    Deploy:
         needs: [Trivy]
         uses: ./.github/workflows/Deploy-server.yml
         secrets: inherit
       