#End to end pipline

name:  DevSecOps End to End Pipeline

on:
    workflow_dispatch:

jobs:

    Code-Quality:
          uses: ./.github/workflows/code-quality.yml

    Secret-Scan:
          uses: ./.github/workflows/secret-scans.yml

    Dependices-Scan:
          uses: ./.github/workflows/dependencies-scan.yml

    Docker-Scan:
          uses: ./.github/workflows/docker-lint.yml

    Build:
          needs: [Code-Quality, Secret-Scan, Dependices-Scan, Docker-Scan]
          uses: ./.github/workflows/Deploy-server.yml
          secrets: inherit

    Trivy:
         needs: [Build]
         uses: ./.github/workflows/image-scan.yml
         secrets: inherit

    Deploy:
         needs: [Trivy]
         uses: ./.github/workflows/docker-build-push.yml
         secrets: inherit
       