# Scan the Dockerfile for issues & CVEs

name: Docker Lint

on:
    workflow_call:

jobs:
        dependency_scan:
            runs-on: ubuntu-latest

            steps:
                - name: Checkout code
                  uses: actions/checkout@v4

                - name: Run Hadolint
                  uses: hadolint/hadolint-action@v3.1.0
                  with:
                    dockerfile: .github/workflows/Dockerfile
