#APLI keys and other secret values should not be committed to the repo
#Gitleaks
name: Secrets Scan

on:
    workflow_call:
    
jobs:

     secret-scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

          with:
             fetch-depth: 0

        - name: Run Gitleaks Scanner
          uses: gitleaks/gitleaks-action@v2

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}